- name: Create Users
  hosts: webserver2
  become: yes
  vars:
    users:
      - helena
      - Aljendro
      - Alex
      - Sameul
      - Alberto
  tasks:
    - name: Create saurabh users
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ users }}"