webservers:
  hosts:
    web1:
      ansible_host: webserver1
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_pass: password
    web2:
      ansible_host: webserver2
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_pass: password

dbservers:
  hosts:
    db1:
      ansible_host: dbserver1
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_pass: password
    db2:
      ansible_host: dbserver2
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_pass: password
