- name: Install web servers
  hosts: all
  tasks:
    - name: Install all apps server
      apt:
        name: "{{ apps }}"
        state: present
        update_cache: yes
      become: true

- name: Copy index.php file and move to the server
  hosts: webservers
  tasks:
    - name: Upload index.php file
      copy:
        src: index.php
        dest: /var/www/html
        mode: 0755
      become: true